### ISSUE TITLE
Any plans to integrate molecule?

### ISSUE THREAD

**Issue by lispc** [nervosnetwork/ckb-std#1]
Syscall results are currently raw bytes.    
Are there any plans to deserialize syscall results into structs using nostd molecule?

**Comment by jjyr** [comment]
I'd rather keep syscall return bytes to keep the interface simple;

Molecule is already supported no_std in the master branch, I am planning to integrate the core types into `ckb-contract-std` as an optional feature.

**Comment by jjyr** [comment]
This project demonstrates how to deserialize molecule structs https://github.com/jjyr/godwoken/blob/switch-to-rust/contracts/main/src/utils.rs#L32

After thinking, I decide do not integrate the molecule into `ckb-contract-std`. Keep the project separated can reduce dependencies, and update individually; another approach is to push the CKB team to make core type library support `no_std`, both are better than integrate molecule types into `ckb-contract-std`.
