### ISSUE TITLE
Stable rust

### ISSUE THREAD

**Issue by blckngm** [nervosnetwork/ckb-std#38]
Now that the default alloc error handler is stabilized, it's possible to build no_std + alloc programs with stable rust.

A drawback is that the default alloc error handler pulls in fmt, so it might increase binary size.

**Comment by blckngm** [comment]
https://github.com/XuJiandong/ckb-std/commit/0eb43ed1c596d3c7cd8d0dd73226ea01a43773c7

https://github.com/XuJiandong/ckb-stable-rust-demo/tree/master

**Comment by blckngm** [comment]
@XuJiandong do you want to submit a PR for this?

**Comment by XuJiandong** [comment]
I'm not sure. Because we need to update capsule and other toolchain after that.

**Comment by blckngm** [comment]
I can update capsule template.

**Comment by blckngm** [comment]
Capsule develop already supports changing rust-toolchain in the `rust-toolchain` file.

**Comment by blckngm** [comment]
I'll submit a PR for this.

**Comment by blckngm** [comment]
Size difference for ckb-std-tests using the default alloc error handler vs custom alloc error handler that does not use fmt: 50936 vs 50544, 392 bytes.
