### ISSUE TITLE
Is there an easier way to get the absolute index of the CellInput load by Source::GroupInput

### ISSUE THREAD

**Issue by EthanYuan** [nervosnetwork/ckb-std#56]
In the contract I'm implementing, I need to find an output that matches the absolute index of the input in the group.

```rust
let input = load_input(index, Source::GroupInput)?;
let input_absolute_index = calculate_input_absolute_index(&input)?;
let output = load_cell(input_absolute_index, Source::Output)?;
```

```rust
fn calculate_input_absolute_index(input: &CellInput) -> Result<usize, Error> {
    load_transaction()?
        .raw()
        .inputs()
        .into_iter()
        .position(|i| i.as_bytes() == input.as_bytes())
        .ok_or(Error::ItemMissing)
}
```

However, the method I'm using is quite inefficient.

**Comment by quake** [comment]
you may use the `QueryIter` and `load_cell_lock_hash`:
```rust
let inputs_index = QueryIter::new(load_cell_lock_hash, Source::Input).filter(hash == current_script_hash).collect()
let outputs_index = QueryIter::new(load_cell_lock_hash, Source::Output).filter(hash == current_script_hash).collect()
inputs_index == outputs_index
```

**Comment by EthanYuan** [comment]
> you may use the `QueryIter` and `load_cell_lock_hash`:
> 
> ```rust
> let inputs_index = QueryIter::new(load_cell_lock_hash, Source::Input).filter(hash == current_script_hash).collect()
> let outputs_index = QueryIter::new(load_cell_lock_hash, Source::Output).filter(hash == current_script_hash).collect()
> inputs_index == outputs_index
> ```

It should not meet my needs, mainly because the lock hash of output is not necessarily the same as input, it can be arbitrary.

**Comment by quake** [comment]
you may just use line one to collect the absolute indexes of current lock script.

**Comment by EthanYuan** [comment]
I did try and got an array of lock_hash instead of an index array. Am I making a mistake somewhere?

```rust
let current_script_hash = load_script_hash()?;
let inputs: Vec<[u8; 32]> = QueryIter::new(load_cell_lock_hash, Source::Input)
    .filter(|hash| hash == &current_script_hash)
    .collect();
```

**Comment by quake** [comment]
use enumerate first then filter or filter_map

**Comment by EthanYuan** [comment]
it works, thank you : )

```rust
let current_script_hash = load_script_hash()?;
let inputs: Vec<(usize, _)> = QueryIter::new(load_cell_lock_hash, Source::Input)
    .enumerate()
    .filter(|(i, hash)| hash == &current_script_hash)
    .collect();
```
