### ISSUE TITLE
[Bug] VM Internal Error: MemWriteOnExecutablePage

### ISSUE THREAD

**Issue by xcshuan** [nervosnetwork/ckb-std#77]
When I upgrade the version of ckb-std from 0.14.0 to 0.15.1 for https://github.com/xcshuan/ecdsa-lock, I can't test the script with env `CAPSULE_TEST_ENV=release` bacause issue below:
```
thread 'tests::test_ecverify' panicked at 'pass verification: Error { kind: Script, inner: TransactionScriptError { source: Inputs[0].Lock, cause: VM Internal Error: MemWriteOnExecutablePage } }', src/tests.rs:79:10
```

Debug mode is ok.

**Comment by quake** [comment]
resolved by https://github.com/nervosnetwork/ckb-std/pull/79

**Comment by quake** [comment]
please upgrade to https://crates.io/crates/ckb-std/0.15.3
