### ISSUE TITLE
Document `high_level::load_cell_data` failure mode

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/ckb-std#99]
[As @XuJiandong noticed](https://github.com/ickb/v1-core/issues/3#issue-2460124809):

> The load_cell_data function can load all cell data at once. However, the cell data might be very large, potentially consuming all available memory in certain scenarios. It is recommended to use the following low-level syscall to load only a portion of the cell data

Could the [load_cell_data docs](https://docs.rs/ckb-std/latest/ckb_std/high_level/fn.load_cell_data.html) be updated to make evident this failure mode?

Keep up the great work :muscle:
Phroi

**Comment by XuJiandong** [comment]
This is an out-of-memory error that can occur with any value requiring `alloc`, such as `Vec`. We can add extra notice to it.

**Comment by phroi** [comment]
Yup yup, that warning seems enough, feel free to close this issue when #101 is merged! :hugs:

Love & Peace, Phroi

**Comment by XuJiandong** [comment]
https://github.com/nervosnetwork/ckb-std/pull/101

**Comment by phroi** [comment]
Thank you!! :pray:
